## 9.1 Add Two Matrices

In [8]:
X = [[1, 2],
     [3, 4]]
Y = [[5, 6],
     [7, 8]]

result = [[X[i][j] + Y[i][j] for j in range(len(X[0]))] for i in range(len(X))]
print(f"Result = {result}")

Result = [[6, 8], [10, 12]]


## 9.2 Multiply Two Matrices

In [9]:
def multiply_matrices(X, Y):
    rows_X = len(X)
    cols_X = len(X[0])
    rows_Y = len(Y)
    cols_Y = len(Y[0])

    if cols_X != rows_Y:
        return "Error: Number of columns in X must be equal to number of rows in Y"

    result = [[0 for _ in range(cols_Y)] for _ in range(rows_X)]

    for i in range(rows_X):
        for j in range(cols_Y):
            for k in range(cols_X):
                result[i][j] += X[i][k] * Y[k][j]
    return result

X = [[1, 2],
     [3, 4]]
Y = [[5, 6],
     [7, 8]]
result = multiply_matrices(X, Y)
print(f"Result = {result}")

Result = [[19, 22], [43, 50]]


## 9.3 Transpose of a Matrix

In [10]:
matrix = [[1, 2],
          [3, 4],
          [5, 6]]

rows = len(matrix)
cols = len(matrix[0])

transposed_matrix_lc = [[matrix[j][i] for j in range(rows)] for i in range(cols)]
print(f"Transpose of the matrix: {transposed_matrix_lc}")

transposed_matrix_zip = list(map(list, zip(*matrix)))
print(f"Transpose of the matrix (using zip): {transposed_matrix_zip}")

Transpose of the matrix: [[1, 3, 5], [2, 4, 6]]
Transpose of the matrix (using zip): [[1, 3, 5], [2, 4, 6]]


## 9.4 Matrix Product (Product of all elements)

In [11]:
import math

test_list = [[1, 4, 5], [7, 3], [4], [46, 7, 3]]

total_product = math.prod([num for sublist in test_list for num in sublist])
print(f"The total element product in lists is: {total_product}")

The total element product in lists is: 1622880


## 9.5 Find Maximum Element in Each Row of a Matrix

In [12]:
matrix = [[3, 4, 1],
          [7, 2, 9],
          [5, 8, 6]]

max_elements = [max(row) for row in matrix]
print(f"Maximum elements in each row are: {max_elements}")

Maximum elements in each row are: [4, 9, 8]


## 9.6 Sum of Each Row and Column in a Matrix

In [13]:
def calculate_row_column_sums(matrix):
    rows = len(matrix)
    cols = len(matrix[0])

    # Calculate row sums
    row_sums = [sum(row) for row in matrix]
    print(f"Row sums: {row_sums}")

    # Calculate column sums
    column_sums = [sum(matrix[r][c] for r in range(rows)) for c in range(cols)]
    print(f"Column sums: {column_sums}")

# Example Usage 1
matrix1 = [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]
print("Matrix 1:")
for row in matrix1: print(row)
calculate_row_column_sums(matrix1)
print()

Matrix 1:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
Row sums: [6, 15, 24]
Column sums: [12, 15, 18]



## 9.7 Check if a Matrix is Symmetric

In [14]:
def is_symmetric(matrix):
    rows = len(matrix)
    cols = len(matrix[0])

    # A symmetric matrix must be square
    if rows != cols:
        return False

    # Check if A[i][j] == A[j][i] for all i, j
    for i in range(rows):
        for j in range(i, cols):  # Iterate from i to avoid redundant checks and self-comparison
            if matrix[i][j] != matrix[j][i]:
                return False
    return True

# Example Usage 1 (Symmetric Matrix)
matrix1 = [[1, 2, 3],
           [2, 4, 5],
           [3, 5, 6]]
print("Matrix 1:")
for row in matrix1: print(row)
if is_symmetric(matrix1):
    print("The matrix is symmetric.")
else:
    print("The matrix is not symmetric.")
print()


Matrix 1:
[1, 2, 3]
[2, 4, 5]
[3, 5, 6]
The matrix is symmetric.



In [15]:
import numpy as np

### 9.1 Add Two Matrices (NumPy)

In [25]:
import numpy as np
X = np.array([[1, 2],
                 [3, 4]])
Y = np.array([[5, 6],
                 [7, 8]])

result_np = X + Y
print(result_np)

[[ 6  8]
 [10 12]]


### 9.2 Multiply Two Matrices (NumPy)

In [26]:
X = np.array([[1, 7, 3],
                 [3, 5, 6],
                 [6, 8, 9]])
Y = np.array([[1, 1, 1, 2],
                 [6, 7, 3, 0],
                 [4, 5, 9, 1]])
result_np = np.dot(X, Y)
print(result_np)

[[ 55  65  49   5]
 [ 57  68  72  12]
 [ 90 107 111  21]]


### 9.3 Transpose of a Matrix (NumPy)

In [27]:
matrix= np.array([[1, 2],
                      [3, 4],
                      [5, 6]])

transposed_matrix = matrix.T
print(transposed_matrix)

[[1 3 5]
 [2 4 6]]


### 9.4 Matrix Product (Product of all elements) (NumPy)

In [28]:
test = [[1, 4, 5], [7, 3], [4], [46, 7, 3]]
flattened_list = [num for sublist in test for num in sublist]
total_product = np.prod(flattened_list)
print(total_product)

1622880


### 9.5 Find Maximum Element in Each Row of a Matrix (NumPy)

In [29]:
matrix = np.array([[3, 4, 1],
                      [7, 2, 9],
                      [5, 8, 6]])

max_elements= np.max(matrix, axis=1)
print(max_elements)

[4 9 8]


### 9.6 Sum of Each Row and Column in a Matrix (NumPy)

In [30]:
def calculate_row_column_sums(matrix):
    matrix= np.array(matrix)

    # Calculate row sums
    row_sums = np.sum(matrix, axis=1)
    print(f"Row sums: {row_sums.tolist()}")

    # Calculate column sums
    column_sums= np.sum(matrix, axis=0)
    print(f"Column sums: {column_sums.tolist()}")

# Example Usage 1
matrix1_np = [[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]]
print("Matrix 1:")
for row in matrix1_np: print(row)
calculate_row_column_sums(matrix1_np)
print()

Matrix 1:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
Row sums: [6, 15, 24]
Column sums: [12, 15, 18]



### 9.7 Check if a Matrix is Symmetric (NumPy)

In [31]:
def is_symmetric(matrix):
    matrix= np.array(matrix)

    # A symmetric matrix must be square
    if matrix.shape[0] != matrix.shape[1]:
        return False

    # Check if A == A.T
    return np.array_equal(matrix, matrix.T)

# Example Usage 1 (Symmetric Matrix)
matrix1_np = [[1, 2, 3],
              [2, 4, 5],
              [3, 5, 6]]
print("Matrix 1:")
for row in matrix1_np: print(row)
if is_symmetric(matrix1_np):
    print("The matrix is symmetric.")
else:
    print("The matrix is not symmetric.")
print()

Matrix 1:
[1, 2, 3]
[2, 4, 5]
[3, 5, 6]
The matrix is symmetric.

